name: Build

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install Apex CLI
        run: deno install -A --unstable -f -n apex https://deno.land/x/apex_cli/apex.ts

      - name: Generator diff test
        run: ./diffcheck.sh
        working-directory: ./testdata

      - name: Is Release?
        if: startswith(github.ref, 'refs/tags/v')
        run: echo "DEPLOY_PACKAGE=true" >> $GITHUB_ENV

      - name: Publish to npm
        if: env.DEPLOY_PACKAGE == 'true'
        run: npm pack && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
